// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzIOlJtokwHsEMnulggyB29fYwOnMXIM',
    appId: '1:931652501025:web:1c9bcfebfc793018d1ad60',
    messagingSenderId: '931652501025',
    projectId: 'n2-desenvolvimentomobile',
    authDomain: 'n2-desenvolvimentomobile.firebaseapp.com',
    storageBucket: 'n2-desenvolvimentomobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsLY-EcbKUc3pu6lCQCp2EvVj1v6GD-I',
    appId: '1:931652501025:android:3e262359892d1987d1ad60',
    messagingSenderId: '931652501025',
    projectId: 'n2-desenvolvimentomobile',
    storageBucket: 'n2-desenvolvimentomobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQ3kU5kHfXaIxgDiksVtTCSDZ-ks3biY',
    appId: '1:931652501025:ios:d6cbe76fcaa57cbed1ad60',
    messagingSenderId: '931652501025',
    projectId: 'n2-desenvolvimentomobile',
    storageBucket: 'n2-desenvolvimentomobile.firebasestorage.app',
    iosBundleId: 'com.example.n2Devmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQ3kU5kHfXaIxgDiksVtTCSDZ-ks3biY',
    appId: '1:931652501025:ios:d6cbe76fcaa57cbed1ad60',
    messagingSenderId: '931652501025',
    projectId: 'n2-desenvolvimentomobile',
    storageBucket: 'n2-desenvolvimentomobile.firebasestorage.app',
    iosBundleId: 'com.example.n2Devmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBzIOlJtokwHsEMnulggyB29fYwOnMXIM',
    appId: '1:931652501025:web:392e46da74c794d1d1ad60',
    messagingSenderId: '931652501025',
    projectId: 'n2-desenvolvimentomobile',
    authDomain: 'n2-desenvolvimentomobile.firebaseapp.com',
    storageBucket: 'n2-desenvolvimentomobile.firebasestorage.app',
  );
}
